### ISSUE TITLE
How to scale when there are multiple queues?

### ISSUE THREAD

**Issue by joebowbeer** [miztiik/scale-eks-with-keda#1]
Thanks for the detailed sample!

How would you scale a deployment that pulls from multiple SQS queues, in which case the desired scale-out should be derived from the SUM of the queue lengths?

As I understand it, multiple triggers are combined with MAX rather than SUM.

This problem can be generalized for multiple triggers of any type. However, whereas the RabbitMQ scaler supports a regex, and the Prometheus trigger supports a sum operation, the SQS scaler does neither.

Can you suggest a way to implement this before the proposal (below) is implemented?

One idea I had was to export the SQS metrics to Prometheus (using [YACE](https://github.com/nerdswords/yet-another-cloudwatch-exporter)) and then use a Prometheus-triggered ScaledObject in KEDA, or replace KEDA with [prometheus-adapter](https://github.com/kubernetes-sigs/prometheus-adapter).

https://github.com/kedacore/keda/issues/2440

**Comment by miztiik** [comment]
Hello @joebowbeer - That is an excellent issue. 

It also makes me wonder what would be a real-life scenario, where one consumer(group of consumers) processes of events from multiple queues? For example - Is it something like orders coming from mobile and web front ends goes to a different queue system to be processed by a group of consumers. 

I like the idea of the trigger based on computed composite metric - https://github.com/kedacore/keda/discussions/2431 This in theory should work very similar to the [composite alarm - AWS Cloudwatch has.](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Create_Composite_Alarm.html)

If you cannot wait, your idea will work. Either you can use prometheus or Compute a composite metric in AWS Cloudwatch - maybe a custom metric and KEDA can use that a trigger. I am happy to discuss this further. Let me know what you think

**Comment by joebowbeer** [comment]
Hi @miztiik thanks for confirming, and for mentioning the possibility of using a custom CW metric. Yes, the scenario is that the queues are partitioned per producer, but there is only a single consumer internally.

**Comment by miztiik** [comment]
@joebowbeer - If you manage to implement a custom CW metric do let me know, I would like to know how you have implemented it.
